name: trash_bin
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  async: ^2.11.0
  flutter:
    sdk: flutter
  geolocator: ^10.0.0
  google_maps_flutter: ^2.4.0
  image_picker: ^1.0.2
  path: ^1.8.3
  path_provider: ^2.1.0
  shared_preferences: ^2.2.0
  sqflite: ^2.3.0
  sqflite_common: ^2.5.0
  sqflite_common_ffi: ^2.3.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
